services:
  web:
    build: .
    command: bash -c "bundle exec rackup config.ru -o 0.0.0.0 -p 8002"
    stdin_open: true
    tty: true
    volumes:
      - .:/api
    ports:
      - "8002:8002"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: back_end_development
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
networks:
  default:
    external: true
    name: front-end
