ruby '3.1.4'
source 'https://rubygems.org'

gem 'activerecord', '~> 7.0'
gem 'bcrypt', '~> 3.1'
gem 'dotenv', '~> 2.7'
gem 'pg', '~> 1.2'
gem 'rake', '~> 13.2'
gem 'sinatra', '~> 2.1'
gem 'sinatra-activerecord', '~> 2.0'
gem 'sinatra-contrib', '~> 2.1'
gem 'webrick', '~> 1.7'
